# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGfEJ04AXz3lELHy4cZ3Q4CySLgC4oLp
"""

import requests

# Base URL for the API
BASE_URL = "https://jsonplaceholder.typicode.com"

# Function to fetch data using a GET request
def fetch_posts():
    print("\n--- Fetching Posts (GET Request) ---")
    endpoint = f"{BASE_URL}/posts"
    response = requests.get(endpoint)

    # Check if the request was successful
    if response.status_code == 200:
        posts = response.json()
        print("Fetched Posts:")
        for post in posts[:3]:  # Display only the first 3 posts for simplicity
            print(f"ID: {post['id']}, Title: {post['title']}")
    else:
        print(f"Failed to fetch posts. Status Code: {response.status_code}")

# Function to create data using a POST request
def create_post():
    print("\n--- Creating a New Post (POST Request) ---")
    endpoint = f"{BASE_URL}/posts"
    # Define the data to send in the POST request body
    data = {
        "title": "My New Post",
        "body": "This is the body of my new post.",
        "userId": 1
    }
    # Send the POST request
    response = requests.post(endpoint, json=data)

    # Check if the request was successful
    if response.status_code == 201:  # HTTP 201: Created
        created_post = response.json()
        print("Post Created Successfully!")
        print(f"ID: {created_post['id']}, Title: {created_post['title']}")
    else:
        print(f"Failed to create post. Status Code: {response.status_code}")

# Main program execution
if __name__ == "__main__":
    print("Welcome to the RESTful API Example")

    # Fetch data using GET
    fetch_posts()

    # Create data using POST
    create_post()

